# Form implementation generated from reading ui file 'dashboard.ui'
#
# Created by: PyQt6 UI code generator 6.1.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets;
from visualisasi import Ui_Dialog;


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 595)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(-1, -1, 801, 571))
        self.widget.setStyleSheet("QWidget#widget {\n"
"background-color:qlineargradient(spread:pad, x1:0.189055, y1:0.545, x2:0.139, y2:0.544682, stop:0.402985 rgba(255, 255, 254, 255), stop:0.507463 rgba(217, 81, 35, 255)); }\n"
"")
        self.widget.setObjectName("widget")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(230, 200, 401, 51))
        self.label.setStyleSheet("font: 75 17pt \"MS Sans Serif\";\n"
"color: rgb(217, 81, 35);\n"
"")
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        self.menuHome = QtWidgets.QMenu(self.menubar)
        self.menuHome.setObjectName("menuHome")
        self.menuBahan_Dasar = QtWidgets.QMenu(self.menubar)
        self.menuBahan_Dasar.setObjectName("menuBahan_Dasar")
        self.menuKeuangan = QtWidgets.QMenu(self.menubar)
        self.menuKeuangan.setObjectName("menuKeuangan")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionInput = QtGui.QAction(MainWindow)
        self.actionInput.setObjectName("actionInput")
        self.actionVisualisasi = QtGui.QAction(MainWindow)
        self.actionVisualisasi.setObjectName("actionVisualisasi")
        self.actionInput_Data_Bahan_Dasar = QtGui.QAction(MainWindow)
        self.actionInput_Data_Bahan_Dasar.setObjectName("actionInput_Data_Bahan_Dasar")
        self.actionInput_Data_Pengeluaran = QtGui.QAction(MainWindow)
        self.actionInput_Data_Pengeluaran.setObjectName("actionInput_Data_Pengeluaran")
        self.actionInput_Data_Beban = QtGui.QAction(MainWindow)
        self.actionInput_Data_Beban.setObjectName("actionInput_Data_Beban")
        self.menuBahan_Dasar.addAction(self.actionInput)
        self.menuBahan_Dasar.addAction(self.actionVisualisasi)
        self.menuKeuangan.addAction(self.actionInput_Data_Bahan_Dasar)
        self.menuKeuangan.addAction(self.actionInput_Data_Pengeluaran)
        self.menuKeuangan.addAction(self.actionInput_Data_Beban)
        self.menubar.addAction(self.menuHome.menuAction())
        self.menubar.addAction(self.menuBahan_Dasar.menuAction())
        self.menubar.addAction(self.menuKeuangan.menuAction())
        self.actionVisualisasi.triggered.connect(self.visualisasiScr)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def visualisasiScr(self):
        self.app = QtWidgets.QApplication(sys.argv)
        self.Dialog = QtWidgets.QDialog()
        self.ui = Ui_Dialog()
        self.ui.setupUi(self.Dialog)
        self.Dialog.show()

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Selamat Datang di Dragonier"))
        self.menuHome.setTitle(_translate("MainWindow", "Home"))
        self.menuBahan_Dasar.setTitle(_translate("MainWindow", "Bahan Dasar"))
        self.menuKeuangan.setTitle(_translate("MainWindow", "Keuangan"))
        self.actionInput.setText(_translate("MainWindow", "Input"))
        self.actionVisualisasi.setText(_translate("MainWindow", "Visualisasi"))
        self.actionInput_Data_Bahan_Dasar.setText(_translate("MainWindow", "Input Data Pemasukan"))
        self.actionInput_Data_Pengeluaran.setText(_translate("MainWindow", "Input Data Pengeluaran"))
        self.actionInput_Data_Beban.setText(_translate("MainWindow", "Input Data Beban"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
